# Generated by Django 4.2.1 on 2023-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Element',
            fields=[
                ('video_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_element_name', models.CharField(max_length=100)),
                ('video_element_duration', models.IntegerField()),
                ('video_element_upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
