# Generated by Django 4.2.1 on 2023-05-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_video_element_videoelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoelement',
            name='video_element_name',
        ),
    ]
