# Generated by Django 4.2.1 on 2023-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_videoelement_video_element_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio_element",
            name="duration",
        ),
        migrations.AddField(
            model_name="audio_element",
            name="end_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audio_element",
            name="start_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
